version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "22:30"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 15
