name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the workflow with debug logging'
        required: false
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov requests-mock black isort
        pip install -e .[dev]
        
    - name: Check formatting
      run: |
        black --check .
        isort --check .
        
    - name: Run tests
      run: |
        if [ "${{ github.event.inputs.debug_enabled }}" = "true" ]; then
          pytest -v --cov-branch --cov-report=xml
        else
          pytest --cov-branch --cov-report=xml
        fi
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}